import { db } from "@workspace/db";
import {
  citiesTable,
  hotelsTable,
  roomsTable,
  reviewsTable,
  amenitiesTable,
  bookingsTable,
} from "@workspace/db/schema";

async function seed() {
  console.log("Seeding database...");

  await db.delete(reviewsTable);
  await db.delete(roomsTable);
  await db.delete(bookingsTable);
  await db.delete(hotelsTable);
  await db.delete(citiesTable);
  await db.delete(amenitiesTable);

  const amenities = await db.insert(amenitiesTable).values([
    { slug: "wifi", name: "Free Wi-Fi", icon: "Wifi" },
    { slug: "pool", name: "Swimming Pool", icon: "Waves" },
    { slug: "spa", name: "Spa & Wellness", icon: "Sparkles" },
    { slug: "gym", name: "Fitness Center", icon: "Dumbbell" },
    { slug: "restaurant", name: "Restaurant", icon: "UtensilsCrossed" },
    { slug: "bar", name: "Bar & Lounge", icon: "Wine" },
    { slug: "parking", name: "Free Parking", icon: "ParkingCircle" },
    { slug: "ac", name: "Air Conditioning", icon: "Wind" },
    { slug: "concierge", name: "Concierge Service", icon: "Bell" },
    { slug: "room-service", name: "Room Service", icon: "ConciergeBell" },
    { slug: "airport-shuttle", name: "Airport Shuttle", icon: "Car" },
    { slug: "business-center", name: "Business Center", icon: "Briefcase" },
    { slug: "beach", name: "Beach Access", icon: "Umbrella" },
    { slug: "tennis", name: "Tennis Court", icon: "CircleDot" },
    { slug: "kids-club", name: "Kids Club", icon: "Baby" },
    { slug: "hammam", name: "Traditional Hammam", icon: "Droplets" },
    { slug: "conference", name: "Conference Rooms", icon: "Users" },
    { slug: "laundry", name: "Laundry Service", icon: "Shirt" },
    { slug: "tv", name: "Satellite TV", icon: "Tv" },
    { slug: "safe", name: "In-room Safe", icon: "Lock" },
  ]).returning();

  console.log(`Inserted ${amenities.length} amenities`);

  const cities = await db.insert(citiesTable).values([
    {
      slug: "algiers",
      name: "Algiers",
      nameAr: "الجزائر",
      region: "Alger",
      description: "The vibrant capital of Algeria, perched on the Mediterranean coast. Known as 'Algiers the White' for its gleaming hillside buildings, the city blends French colonial architecture with Berber and Ottoman heritage. Home to the UNESCO-listed Casbah, stunning bay views, and a thriving cultural scene.",
      imageUrl: "https://images.unsplash.com/photo-1548199569-f5a027a5e38c?w=800&q=80",
    },
    {
      slug: "oran",
      name: "Oran",
      nameAr: "وهران",
      region: "Oran",
      description: "Algeria's second largest city and the 'Radiant City' of the west. Oran is a cosmopolitan port city with a rich musical heritage — birthplace of Raï music. Features beautiful beaches, Spanish fortresses, French cathedrals, and a lively Mediterranean atmosphere.",
      imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    },
    {
      slug: "constantine",
      name: "Constantine",
      nameAr: "قسنطينة",
      region: "Constantine",
      description: "The 'City of Bridges' dramatically perched on a rocky plateau above the Rhumel gorge. One of Africa's oldest cities with a history spanning 2,500 years. Famous for its spectacular suspension bridges, ancient Numidian ruins, and the Emir Abdelkader Mosque.",
      imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
    },
    {
      slug: "annaba",
      name: "Annaba",
      nameAr: "عنابة",
      region: "Annaba",
      description: "The 'City of Jujube Trees', Algeria's fourth largest city on the northeastern Mediterranean coast. Annaba offers beautiful beaches, Roman ruins at Hippo Regius, and excellent seafood. The birthplace of Saint Augustine and a gateway to the Edough mountains.",
      imageUrl: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
    },
    {
      slug: "tlemcen",
      name: "Tlemcen",
      nameAr: "تلمسان",
      region: "Tlemcen",
      description: "The 'City of Art and History', Tlemcen was the glorious capital of the Zianid dynasty. This cultural jewel of western Algeria is renowned for its exquisite Moorish architecture, ancient medina, Grand Mosque, and Mansourah ruins. A UNESCO heritage treasure.",
      imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
    },
    {
      slug: "tamanrasset",
      name: "Tamanrasset",
      nameAr: "تمنراست",
      region: "Tamanrasset",
      description: "Gateway to the Sahara and the majestic Hoggar Mountains. This legendary desert city is the heart of Tuareg culture. Surrounded by the stunning Ahaggar National Park, ancient rock art, and the dramatic peak of Mount Tahat, Algeria's highest summit.",
      imageUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80",
    },
    {
      slug: "ghardaia",
      name: "Ghardaïa",
      nameAr: "غرداية",
      region: "M'zab Valley",
      description: "A UNESCO World Heritage city in the M'zab Valley. Ghardaïa is a living museum of Ibadite Muslim culture with its five medieval walled cities. The unique pentagonal urban planning of these 11th-century ksours has influenced architects worldwide including Le Corbusier.",
      imageUrl: "https://images.unsplash.com/photo-1537561983432-9c10a7c70dff?w=800&q=80",
    },
    {
      slug: "bejaia",
      name: "Béjaïa",
      nameAr: "بجاية",
      region: "Béjaïa",
      description: "A stunning Mediterranean port city nestled between the Soummam valley and the Gulf of Béjaïa. Known for its turquoise waters, Cap Carbon lighthouse, and Gouraya National Park. This Kabyle coastal gem offers some of Algeria's most beautiful beaches.",
      imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    },
  ]).returning();

  console.log(`Inserted ${cities.length} cities`);

  const cityMap = new Map(cities.map((c) => [c.slug, c.id]));

  const hotels = await db.insert(hotelsTable).values([
    {
      name: "Hôtel El Djazaïr",
      slug: "hotel-el-djazair",
      cityId: cityMap.get("algiers")!,
      address: "24 Rue Souidani Boudjemaa, Algiers",
      stars: 5,
      rating: 4.7,
      reviewCount: 328,
      pricePerNight: 18500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
        "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
        "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80",
        "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80",
      ],
      amenities: ["wifi", "pool", "spa", "gym", "restaurant", "bar", "parking", "ac", "concierge", "room-service", "business-center"],
      isFeatured: true,
      description: "A legendary five-star palace nestled among lush gardens in the heart of Algiers, Hôtel El Djazaïr (formerly the Saint-George Hotel) has hosted luminaries from Eisenhower to De Gaulle. This iconic establishment blends Moorish architecture with modern luxury, offering panoramic views of the Bay of Algiers.",
      latitude: 36.7538,
      longitude: 3.0588,
      checkInTime: "14:00",
      checkOutTime: "12:00",
      nearbyAttractions: ["Casbah of Algiers (UNESCO)", "Martyrs' Memorial", "Botanical Garden of Hamma", "Bardo National Museum"],
      policies: "No smoking indoors. Pets not allowed. Children welcome. Valid ID required at check-in.",
    },
    {
      name: "Sofitel Algiers Hamma Garden",
      slug: "sofitel-algiers-hamma",
      cityId: cityMap.get("algiers")!,
      address: "172 Rue Hassiba Ben Bouali, El Hamma, Algiers",
      stars: 5,
      rating: 4.5,
      reviewCount: 241,
      pricePerNight: 22000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1614267157481-ca2b81ac6fcc?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1614267157481-ca2b81ac6fcc?w=800&q=80",
        "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
        "https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?w=800&q=80",
      ],
      amenities: ["wifi", "pool", "spa", "gym", "restaurant", "bar", "parking", "ac", "concierge", "room-service", "airport-shuttle", "business-center", "conference"],
      isFeatured: true,
      description: "Sofitel Algiers Hamma Garden is a contemporary luxury hotel offering exceptional comfort adjacent to the famous Botanical Garden of El Hamma. The hotel features 178 elegantly appointed rooms and suites with French Art de Vivre, a world-class spa, rooftop pool with city views, and gourmet dining.",
      latitude: 36.7325,
      longitude: 3.0614,
      checkInTime: "15:00",
      checkOutTime: "12:00",
      nearbyAttractions: ["El Hamma Botanical Garden", "African Union HQ", "Bay of Algiers", "Algiers Zoo"],
      policies: "No smoking indoors. Pets allowed (small dogs only). Valet parking available.",
    },
    {
      name: "Sheraton Club des Pins Resort",
      slug: "sheraton-club-des-pins",
      cityId: cityMap.get("algiers")!,
      address: "Club des Pins, Staouéli, Algiers",
      stars: 5,
      rating: 4.6,
      reviewCount: 189,
      pricePerNight: 20000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
        "https://images.unsplash.com/photo-1561501900-3701fa6a0864?w=800&q=80",
      ],
      amenities: ["wifi", "pool", "spa", "gym", "restaurant", "bar", "parking", "ac", "concierge", "beach", "tennis", "kids-club", "business-center"],
      isFeatured: true,
      description: "Set within a magnificent pine forest on the Mediterranean coast, Sheraton Club des Pins Resort & Towers is one of Algeria's premier beachfront resorts. This sprawling complex offers direct beach access, multiple pools, water sports, and luxurious accommodations.",
      latitude: 36.7156,
      longitude: 2.9023,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      nearbyAttractions: ["Sidi Fredj Port", "Tipaza Roman Ruins", "Chenoua Beach", "Club des Pins Beach"],
      policies: "Non-smoking property. Beach towels provided. Water sports available at extra cost.",
    },
    {
      name: "Le Méridien Oran Hotel & Convention Centre",
      slug: "le-meridien-oran",
      cityId: cityMap.get("oran")!,
      address: "Complexe Touristique SNED, Oran",
      stars: 5,
      rating: 4.4,
      reviewCount: 156,
      pricePerNight: 17500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
        "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
        "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
      ],
      amenities: ["wifi", "pool", "spa", "gym", "restaurant", "bar", "parking", "ac", "concierge", "room-service", "conference", "business-center", "airport-shuttle"],
      isFeatured: true,
      description: "Le Méridien Oran Hotel & Convention Centre is Oran's most prestigious address, offering spectacular views of the Mediterranean and the Murdjadjo mountain. The hotel features 254 luxuriously appointed rooms and suites, a world-class convention center, rooftop terrace, and the finest dining options in western Algeria.",
      latitude: 35.6976,
      longitude: -0.6337,
      checkInTime: "14:00",
      checkOutTime: "12:00",
      nearbyAttractions: ["Santa Cruz Fort", "Ahmed Zabana Museum", "Oran's Front de Mer", "Bey Palace"],
      policies: "No smoking. Free airport shuttle by reservation. Business lounge available.",
    },
    {
      name: "Hôtel Royal Oran",
      slug: "hotel-royal-oran",
      cityId: cityMap.get("oran")!,
      address: "Boulevard de la Soummam, Oran",
      stars: 4,
      rating: 4.2,
      reviewCount: 98,
      pricePerNight: 12000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
      ],
      amenities: ["wifi", "restaurant", "bar", "parking", "ac", "room-service", "gym", "hammam"],
      isFeatured: false,
      description: "A refined four-star hotel in the heart of Oran offering elegant accommodation and exceptional Algerian hospitality. Hôtel Royal Oran combines traditional architecture with modern amenities, featuring an authentic hammam, rooftop restaurant with panoramic city views.",
      latitude: 35.6892,
      longitude: -0.6308,
      checkInTime: "14:00",
      checkOutTime: "12:00",
      nearbyAttractions: ["Oran Cathedral", "City Hall", "Place du 1er Novembre", "Théâtre Régional d'Oran"],
      policies: "No smoking. Hammam available for extra charge. Traditional Raï music evenings on weekends.",
    },
    {
      name: "Hôtel Cirta Constantine",
      slug: "hotel-cirta-constantine",
      cityId: cityMap.get("constantine")!,
      address: "Place de la Nation, Constantine",
      stars: 4,
      rating: 4.3,
      reviewCount: 112,
      pricePerNight: 10500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80",
        "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80",
      ],
      amenities: ["wifi", "restaurant", "bar", "parking", "ac", "room-service", "gym", "concierge"],
      isFeatured: false,
      description: "Hôtel Cirta stands majestically above the dramatic Rhumel gorge, offering breathtaking views of Constantine's famous bridges. Named after the ancient Numidian name for Constantine, this four-star hotel captures the spirit of Algeria's most dramatic city.",
      latitude: 36.3650,
      longitude: 6.6147,
      checkInTime: "14:00",
      checkOutTime: "12:00",
      nearbyAttractions: ["Sidi M'Cid Bridge", "Emir Abdelkader Mosque", "Constantine Museum", "Tiddis Roman Ruins"],
      policies: "No smoking indoors. Guided gorge tours available through concierge.",
    },
    {
      name: "Grand Hôtel Constantine",
      slug: "grand-hotel-constantine",
      cityId: cityMap.get("constantine")!,
      address: "Rue Didouche Mourad, Constantine",
      stars: 5,
      rating: 4.5,
      reviewCount: 87,
      pricePerNight: 15000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80",
        "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80",
      ],
      amenities: ["wifi", "pool", "spa", "gym", "restaurant", "bar", "parking", "ac", "concierge", "room-service", "hammam", "conference"],
      isFeatured: true,
      description: "The Grand Hôtel Constantine is the crown jewel of the City of Bridges, combining palatial luxury with the dramatic landscape of Algeria's most ancient city. From its elevated position, guests enjoy unparalleled views of the vertiginous Rhumel gorges.",
      latitude: 36.3700,
      longitude: 6.6200,
      checkInTime: "15:00",
      checkOutTime: "12:00",
      nearbyAttractions: ["Sidi Rached Bridge", "Palace of Ahmed Bey", "Cirta Museum", "Souk El Asr"],
      policies: "No smoking. Formal attire required in main restaurant for dinner.",
    },
    {
      name: "Hôtel Seybouse Annaba",
      slug: "hotel-seybouse-annaba",
      cityId: cityMap.get("annaba")!,
      address: "Avenue de l'ALN, Annaba",
      stars: 4,
      rating: 4.0,
      reviewCount: 73,
      pricePerNight: 9500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
        "https://images.unsplash.com/photo-1561501900-3701fa6a0864?w=800&q=80",
      ],
      amenities: ["wifi", "pool", "restaurant", "bar", "parking", "ac", "gym", "beach"],
      isFeatured: false,
      description: "Hôtel Seybouse sits at the heart of Annaba, offering comfortable accommodation and easy access to the city's legendary beaches and Roman heritage. The hotel features a rooftop terrace with views of the Mediterranean and a restaurant specializing in fresh Annaba seafood.",
      latitude: 36.9003,
      longitude: 7.7616,
      checkInTime: "14:00",
      checkOutTime: "12:00",
      nearbyAttractions: ["Hippo Regius Roman Ruins", "Basilica of St. Augustine", "Annaba Beach", "Seraïdi Mountain Village"],
      policies: "No smoking indoors. Beach shuttle available. Fresh seafood daily.",
    },
    {
      name: "Hôtel Zianides Tlemcen",
      slug: "hotel-zianides-tlemcen",
      cityId: cityMap.get("tlemcen")!,
      address: "Rue Khaled Ibn El Walid, Tlemcen",
      stars: 5,
      rating: 4.6,
      reviewCount: 94,
      pricePerNight: 16000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800&q=80",
        "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
      ],
      amenities: ["wifi", "pool", "spa", "gym", "restaurant", "bar", "parking", "ac", "concierge", "room-service", "hammam"],
      isFeatured: true,
      description: "Named in honor of the medieval Zianid dynasty, Hôtel Zianides is a palace of Moorish luxury in Algeria's cultural capital. The hotel's architecture is a masterpiece of Andalusian art with intricate zellige tilework, carved stucco, and cedar wood ceilings.",
      latitude: 34.8778,
      longitude: -1.3153,
      checkInTime: "14:00",
      checkOutTime: "12:00",
      nearbyAttractions: ["Grand Mosque of Tlemcen", "Bab El Karmadine", "Mansourah Ruins", "Lalla Setti Forest"],
      policies: "No smoking. Traditional dress code respected in common areas. Hammam by appointment.",
    },
    {
      name: "Auberge de l'Atakor Tamanrasset",
      slug: "auberge-atakor-tamanrasset",
      cityId: cityMap.get("tamanrasset")!,
      address: "Route de l'Aéroport, Tamanrasset",
      stars: 3,
      rating: 4.1,
      reviewCount: 156,
      pricePerNight: 7500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80",
        "https://images.unsplash.com/photo-1537561983432-9c10a7c70dff?w=800&q=80",
      ],
      amenities: ["wifi", "restaurant", "parking", "ac", "concierge", "airport-shuttle"],
      isFeatured: false,
      description: "Gateway to the legendary Saharan wilderness, Auberge de l'Atakor is the premier desert retreat in Tamanrasset. Built in traditional Tuareg architectural style using local stone, the auberge offers authentic Saharan hospitality with an unobstructed view of the star-filled desert sky.",
      latitude: 22.7852,
      longitude: 5.5228,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      nearbyAttractions: ["Hoggar Mountains", "Assekrem Plateau", "Tazrouk Village", "In Gall Rock Paintings"],
      policies: "Desert excursions must be booked in advance. Bring warm clothing for desert nights.",
    },
    {
      name: "Hôtel Rostémides Ghardaïa",
      slug: "hotel-rostemides-ghardaia",
      cityId: cityMap.get("ghardaia")!,
      address: "Zone Touristique, Ghardaïa",
      stars: 3,
      rating: 4.0,
      reviewCount: 89,
      pricePerNight: 6500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1537561983432-9c10a7c70dff?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1537561983432-9c10a7c70dff?w=800&q=80",
        "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80",
      ],
      amenities: ["wifi", "restaurant", "parking", "ac", "pool", "concierge"],
      isFeatured: false,
      description: "Nestled at the entrance of the M'zab Valley, Hôtel Rostémides offers a comfortable base for exploring the UNESCO World Heritage cities of the Ghardaïa pentapolis. Guests can tour the ancient cities with expert local guides.",
      latitude: 32.4908,
      longitude: 3.6673,
      checkInTime: "14:00",
      checkOutTime: "12:00",
      nearbyAttractions: ["Ghardaïa Old City (UNESCO)", "Béni Isguen", "M'zab Valley", "Ain Sefra"],
      policies: "Modest dress required when visiting the old cities. Photography restrictions in some areas.",
    },
    {
      name: "Hôtel Gouraya Béjaïa",
      slug: "hotel-gouraya-bejaia",
      cityId: cityMap.get("bejaia")!,
      address: "Avenue des Frères Amrani, Béjaïa",
      stars: 4,
      rating: 4.4,
      reviewCount: 128,
      pricePerNight: 11000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
      images: [
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
        "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
      ],
      amenities: ["wifi", "pool", "restaurant", "bar", "parking", "ac", "gym", "beach", "spa"],
      isFeatured: true,
      description: "Hôtel Gouraya commands a prime position overlooking the magnificent Gulf of Béjaïa. This four-star coastal retreat features rooms with panoramic sea views, a stunning infinity pool, and direct access to some of Algeria's most beautiful turquoise beaches.",
      latitude: 36.7509,
      longitude: 5.0567,
      checkInTime: "14:00",
      checkOutTime: "12:00",
      nearbyAttractions: ["Gouraya National Park", "Cap Carbon Lighthouse", "Pic des Singes", "Aokas Beach"],
      policies: "No smoking on terraces. Snorkeling equipment for rent. Beach volleyball available.",
    },
  ]).returning();

  console.log(`Inserted ${hotels.length} hotels`);

  const hotelMap = new Map(hotels.map((h) => [h.slug, h.id]));

  await db.insert(roomsTable).values([
    {
      hotelId: hotelMap.get("hotel-el-djazair")!,
      name: "Superior Room",
      type: "Standard",
      pricePerNight: 18500,
      capacity: 2,
      bedType: "King",
      size: 35,
      amenities: ["wifi", "ac", "safe", "tv", "room-service"],
      imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-el-djazair")!,
      name: "Deluxe Garden View",
      type: "Deluxe",
      pricePerNight: 24000,
      capacity: 2,
      bedType: "King",
      size: 42,
      amenities: ["wifi", "ac", "safe", "tv", "room-service", "minibar"],
      imageUrl: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-el-djazair")!,
      name: "Junior Suite",
      type: "Suite",
      pricePerNight: 38000,
      capacity: 3,
      bedType: "King",
      size: 65,
      amenities: ["wifi", "ac", "safe", "tv", "room-service", "minibar", "bathtub"],
      imageUrl: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("sofitel-algiers-hamma")!,
      name: "Superior Room",
      type: "Standard",
      pricePerNight: 22000,
      capacity: 2,
      bedType: "King",
      size: 38,
      amenities: ["wifi", "ac", "safe", "tv", "room-service"],
      imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("sofitel-algiers-hamma")!,
      name: "Luxury Suite",
      type: "Suite",
      pricePerNight: 48000,
      capacity: 4,
      bedType: "King",
      size: 90,
      amenities: ["wifi", "ac", "safe", "tv", "room-service", "minibar", "bathtub"],
      imageUrl: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("sheraton-club-des-pins")!,
      name: "Beach View Room",
      type: "Standard",
      pricePerNight: 20000,
      capacity: 2,
      bedType: "King",
      size: 40,
      amenities: ["wifi", "ac", "safe", "tv", "room-service", "balcony"],
      imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("sheraton-club-des-pins")!,
      name: "Garden Bungalow",
      type: "Bungalow",
      pricePerNight: 28000,
      capacity: 2,
      bedType: "King",
      size: 55,
      amenities: ["wifi", "ac", "safe", "tv", "room-service", "terrace"],
      imageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("le-meridien-oran")!,
      name: "Classic Room",
      type: "Standard",
      pricePerNight: 17500,
      capacity: 2,
      bedType: "Queen",
      size: 32,
      amenities: ["wifi", "ac", "safe", "tv", "room-service"],
      imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("le-meridien-oran")!,
      name: "Sea View Suite",
      type: "Suite",
      pricePerNight: 35000,
      capacity: 3,
      bedType: "King",
      size: 75,
      amenities: ["wifi", "ac", "safe", "tv", "room-service", "minibar", "bathtub"],
      imageUrl: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-royal-oran")!,
      name: "Standard Room",
      type: "Standard",
      pricePerNight: 12000,
      capacity: 2,
      bedType: "Double",
      size: 28,
      amenities: ["wifi", "ac", "tv"],
      imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-cirta-constantine")!,
      name: "Gorge View Room",
      type: "Standard",
      pricePerNight: 10500,
      capacity: 2,
      bedType: "King",
      size: 30,
      amenities: ["wifi", "ac", "tv", "room-service"],
      imageUrl: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-cirta-constantine")!,
      name: "Bridge Panorama Suite",
      type: "Suite",
      pricePerNight: 18000,
      capacity: 3,
      bedType: "King",
      size: 60,
      amenities: ["wifi", "ac", "tv", "room-service", "bathtub", "minibar"],
      imageUrl: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("grand-hotel-constantine")!,
      name: "Deluxe Room",
      type: "Deluxe",
      pricePerNight: 15000,
      capacity: 2,
      bedType: "King",
      size: 40,
      amenities: ["wifi", "ac", "safe", "tv", "room-service", "minibar"],
      imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-seybouse-annaba")!,
      name: "Standard Room",
      type: "Standard",
      pricePerNight: 9500,
      capacity: 2,
      bedType: "Double",
      size: 28,
      amenities: ["wifi", "ac", "tv"],
      imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-seybouse-annaba")!,
      name: "Sea View Room",
      type: "Deluxe",
      pricePerNight: 13000,
      capacity: 2,
      bedType: "King",
      size: 35,
      amenities: ["wifi", "ac", "tv", "room-service", "balcony"],
      imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-zianides-tlemcen")!,
      name: "Moorish Deluxe Room",
      type: "Deluxe",
      pricePerNight: 16000,
      capacity: 2,
      bedType: "King",
      size: 45,
      amenities: ["wifi", "ac", "safe", "tv", "room-service"],
      imageUrl: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-zianides-tlemcen")!,
      name: "Royal Andalusian Suite",
      type: "Suite",
      pricePerNight: 32000,
      capacity: 4,
      bedType: "King",
      size: 85,
      amenities: ["wifi", "ac", "safe", "tv", "room-service", "minibar"],
      imageUrl: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("auberge-atakor-tamanrasset")!,
      name: "Desert Room",
      type: "Standard",
      pricePerNight: 7500,
      capacity: 2,
      bedType: "Double",
      size: 25,
      amenities: ["wifi", "ac", "tv"],
      imageUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("auberge-atakor-tamanrasset")!,
      name: "Saharan Tent Suite",
      type: "Suite",
      pricePerNight: 14000,
      capacity: 2,
      bedType: "King",
      size: 40,
      amenities: ["wifi", "ac"],
      imageUrl: "https://images.unsplash.com/photo-1537561983432-9c10a7c70dff?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-rostemides-ghardaia")!,
      name: "Standard Room",
      type: "Standard",
      pricePerNight: 6500,
      capacity: 2,
      bedType: "Double",
      size: 24,
      amenities: ["wifi", "ac", "tv"],
      imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-gouraya-bejaia")!,
      name: "Sea View Room",
      type: "Standard",
      pricePerNight: 11000,
      capacity: 2,
      bedType: "King",
      size: 32,
      amenities: ["wifi", "ac", "tv", "balcony"],
      imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    },
    {
      hotelId: hotelMap.get("hotel-gouraya-bejaia")!,
      name: "Panoramic Suite",
      type: "Suite",
      pricePerNight: 22000,
      capacity: 3,
      bedType: "King",
      size: 60,
      amenities: ["wifi", "ac", "tv", "balcony", "bathtub", "minibar"],
      imageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
    },
  ]);

  console.log("Inserted rooms");

  await db.insert(reviewsTable).values([
    {
      hotelId: hotelMap.get("hotel-el-djazair")!,
      guestName: "Marie-Claire Dubois",
      guestCountry: "France",
      rating: 5.0,
      title: "An unforgettable Algerian treasure",
      comment: "Hôtel El Djazaïr is extraordinary. The gardens are magical, the history palpable, and the service impeccable. Waking up to views of the Mediterranean while surrounded by a century-old park is something I will cherish forever.",
      date: "2026-02-15",
      categories: { cleanliness: 5, location: 5, service: 5, value: 4.5 },
    },
    {
      hotelId: hotelMap.get("hotel-el-djazair")!,
      guestName: "Ahmed Benali",
      guestCountry: "Algeria",
      rating: 4.5,
      title: "Algeria's most iconic hotel",
      comment: "I've stayed here several times for business and it never disappoints. The gardens are truly spectacular — like an oasis in the heart of Algiers. The restaurant serves excellent Algerian-Mediterranean cuisine.",
      date: "2026-01-20",
      categories: { cleanliness: 4.5, location: 5, service: 4.5, value: 4 },
    },
    {
      hotelId: hotelMap.get("sofitel-algiers-hamma")!,
      guestName: "James Richardson",
      guestCountry: "United Kingdom",
      rating: 4.5,
      title: "Excellent business hotel with great amenities",
      comment: "Stayed for a week during business meetings. The hotel is extremely well-run, the rooms are spacious and modern, and the rooftop pool is a wonderful way to unwind after a busy day.",
      date: "2026-02-28",
      categories: { cleanliness: 5, location: 4, service: 4.5, value: 4 },
    },
    {
      hotelId: hotelMap.get("sheraton-club-des-pins")!,
      guestName: "Fatima El Amine",
      guestCountry: "Morocco",
      rating: 4.5,
      title: "Perfect beachside escape",
      comment: "The Club des Pins resort is beautiful! The pine forest setting with beach access is unique and very relaxing. The pool complex is fantastic for families.",
      date: "2026-01-10",
      categories: { cleanliness: 4.5, location: 5, service: 4, value: 4.5 },
    },
    {
      hotelId: hotelMap.get("le-meridien-oran")!,
      guestName: "Carlos Mendez",
      guestCountry: "Spain",
      rating: 4.0,
      title: "Great hotel in a wonderful city",
      comment: "Le Méridien Oran exceeded expectations. The views of the Mediterranean from our suite were stunning, and the hotel's location makes it easy to explore Oran's fascinating history.",
      date: "2026-02-05",
      categories: { cleanliness: 4, location: 4.5, service: 4, value: 4 },
    },
    {
      hotelId: hotelMap.get("hotel-zianides-tlemcen")!,
      guestName: "Isabella Conti",
      guestCountry: "Italy",
      rating: 5.0,
      title: "A masterpiece of Moorish luxury",
      comment: "I've traveled to Morocco, Andalusia, and Turkey, but Hôtel Zianides in Tlemcen surpassed them all in authentic Islamic architecture and hospitality. The zellige tiles, carved stucco, and cedar ceilings are breathtaking.",
      date: "2026-03-05",
      categories: { cleanliness: 5, location: 5, service: 5, value: 4.5 },
    },
    {
      hotelId: hotelMap.get("auberge-atakor-tamanrasset")!,
      guestName: "David Thompson",
      guestCountry: "Australia",
      rating: 4.5,
      title: "Sahara stargazing paradise",
      comment: "The Auberge de l'Atakor was the perfect base for our Hoggar Mountains expedition. The Tuareg guides were exceptional. Sleeping under the Saharan stars was a life-changing experience.",
      date: "2026-01-25",
      categories: { cleanliness: 4, location: 5, service: 4.5, value: 5 },
    },
    {
      hotelId: hotelMap.get("hotel-gouraya-bejaia")!,
      guestName: "Yasmine Moussaoui",
      guestCountry: "Algeria",
      rating: 4.5,
      title: "Algeria's most beautiful coastal hotel",
      comment: "Béjaïa is Algeria's best-kept secret and Hôtel Gouraya is the ideal way to experience it. The turquoise water views from my room were absolutely stunning.",
      date: "2026-02-20",
      categories: { cleanliness: 4.5, location: 5, service: 4.5, value: 4.5 },
    },
  ]);

  console.log("Inserted reviews");
  console.log("Seeding complete!");
}

seed().catch(console.error).finally(() => process.exit(0));
